### ISSUE TITLE
wotero.js 报错：saveItemToDatabase::line 2540 data:no

### ISSUE THREAD

**Issue by thatmee** [imzhangjinming/Wotero#21]
![Snipaste_2024-01-16_15-49-46](https://github.com/imzhangjinming/Wotero/assets/57983279/e93e0aeb-93bb-4b61-90f6-a738874777de)

zotero报错如上

手动同步和自动同步均遇到这一问题

- zotero版本：6.0.30

**Comment by imzhangjinming** [comment]
@thatmee 你好，我会在寒假尽力修改，最近半个学期都太忙 :dizzy_face: :disappointed_relieved:

**Comment by imzhangjinming** [comment]
@thatmee  bug已修复，请下载最新[release](https://github.com/imzhangjinming/Wotero/releases/latest)使用

**Comment by thatmee** [comment]
感谢！
